export const DEFINIR_OPERACION = 'DEFINIR_OPERACION';
export const MOSTRAR_OPERACION = 'MOSTRAR_OPERACION';
export const MOSTRAR_RESULTADO = 'MOSTRAR_RESULTADO';
export const RESETEAR_OPERACION = 'RESETEAR_OPERACION';
export const RESETEAR_CALCULADORA = 'RESETEAR_CALCULADORA';
